package org.jitsi.jicofo.db;

public enum UserActionEnum {
    JOIN_CONFERENCE,
    LEAVE_CONFERENCE,
    MUTE_AUDIO,
    MUTE_VIDEO,
    START_RECORDING,
    STOP_RECORDING,
    START_TRANSCRIPTION,
    STOP_TRANSCRIPTION,
    START_VISITOR_CONFERENCE,
    LEAVE_VISITOR_CONFERENCE;
}
